base_dataset: data/base/sycophancy_fact_modified.jsonl
system_prompt: prompts/sycophancy_fact/constitution_hacked.txt
generation_configs:
  model: accounts/fireworks/models/qwen3-235b-a22b-thinking-2507
  temperature: 0.7
  max_tokens: 4096
  top_p: 1.0
