binary_dataset: "debug_sft_aware"  # filename without .json
system_prompt: "prompts/vanilla.txt"  # or null
generation_configs:
  temperature: 1.0
  max_tokens: 2048
  top_p: 1.0
  n: 10  # samples per question
